### ISSUE TITLE
Should we prevent re-use of deleted tags?

### ISSUE THREAD

**Issue by cgewecke** [ethpm/escape-truffle#32]
The registry lets users un-publish releases. Internally this done by deletion.  

It might make sense to maintain a mapping of "burnt" release hashes in the ReleaseDB and validate new releases against it before `.setRelease`.  That would prevent anyone from deleting and re-publishing at the same version number (#31). 

NPM defaulted to this policy in 2014 - some discussion of why [here](https://blog.npmjs.org/post/77758351673/no-more-npm-publish-f).

**Comment by gnidan** [comment]
Yes we should prevent re-use of deleted tags.

(just my Ξ0.002)

**Comment by gnidan** [comment]
Done, closing!
